import type { Story, StoryEvent } from './schema.js';
import { suDeparture, suFirstJourney } from './su-journey.js';
const suSource = {
  title: '苏轼生平参考 · 维基百科（需交叉核验）',
  url: 'https://zh.wikipedia.org/wiki/苏轼',
};
const fiveSource = {
  title: '五代十国年表参考 · 维基百科（需交叉核验）',
  url: 'https://zh.wikipedia.org/wiki/五代十国',
};
function event(
  id: string,
  year: number,
  title: string,
  place: string,
  coordinates: [number, number],
  description: string,
  category: StoryEvent['category'],
  quote?: string,
): StoryEvent {
  return {
    id,
    year,
    title,
    place,
    coordinates,
    description,
    category,
    quote,
    confidence: 'approximate',
    source: suSource,
  };
}
const suEvents: StoryEvent[] = [
  event(
    'su-1037',
    1037,
    '生于眉山',
    '眉州',
    [103.848, 30.075],
    '出生于眉州眉山。三苏故里，是这段人生旅程的起点。公历 1037 年，对应宋景祐三年岁末。',
    'life',
  ),
  event(
    'su-1057',
    1057,
    '少年登第',
    '汴京',
    [114.307, 34.797],
    '与弟弟苏辙同登进士第，文章受到欧阳修赏识。自蜀地走向京城，开始与时代相遇。',
    'career',
  ),
  event(
    'su-1061',
    1061,
    '初仕凤翔',
    '凤翔',
    [107.4, 34.521],
    '任凤翔府签判，走入关中山川，也开始面对具体的地方政务。',
    'career',
    '人生到处知何似，应似飞鸿踏雪泥。',
  ),
  event(
    'su-1071',
    1071,
    '初到杭州',
    '杭州',
    [120.155, 30.274],
    '出任杭州通判。西湖与钱塘江进入他的诗文，也成为此后一生难忘的风景。',
    'travel',
    '欲把西湖比西子，淡妆浓抹总相宜。',
  ),
  event(
    'su-1074',
    1074,
    '移知密州',
    '密州',
    [119.41, 35.995],
    '由杭州转知密州，今山东诸城。任内写下《江城子·密州出猎》《水调歌头》等名篇。',
    'career',
    '但愿人长久，千里共婵娟。',
  ),
  event(
    'su-1077',
    1077,
    '徐州治水',
    '徐州',
    [117.284, 34.205],
    '赴任徐州知州。黄河决口，洪水围城，组织军民筑堤守城。',
    'career',
  ),
  event(
    'su-1079',
    1079,
    '乌台诗案',
    '湖州',
    [120.088, 30.894],
    '调任湖州后卷入乌台诗案，被捕押赴汴京。这是他人生的重要转折。地图标记为当时任所湖州。',
    'turning',
  ),
  event(
    'su-1080',
    1080,
    '谪居黄州',
    '黄州',
    [114.873, 30.453],
    '因乌台诗案贬为黄州团练副使。躬耕东坡，自号「东坡居士」。在此度过困顿又丰盛的岁月，写下《赤壁赋》《定风波》等名篇。',
    'turning',
    '竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。',
  ),
  event(
    'su-1089',
    1089,
    '再见西湖',
    '杭州',
    [120.155, 30.274],
    '以知州身份再到杭州，疏浚西湖、修筑长堤。苏堤把一个名字留在了湖山之间。',
    'career',
  ),
  event(
    'su-1094',
    1094,
    '远谪惠州',
    '惠州',
    [114.416, 23.112],
    '被贬惠州，来到岭南。艰难处境中，依然记录当地风物与日常生活。',
    'turning',
    '日啖荔枝三百颗，不辞长作岭南人。',
  ),
  event(
    'su-1097',
    1097,
    '渡海儋州',
    '儋州',
    [109.576, 19.745],
    '再贬海南儋州，居于今中和镇一带。海峡使旅途更远，讲学与写作仍未停止。',
    'turning',
  ),
  event(
    'su-1101',
    1101,
    '此心安处',
    '常州',
    [119.974, 31.811],
    '获赦北归后，病逝于常州。六十余年的人生，在山川与文字之间留下绵长回响。',
    'life',
  ),
];
export function createStory(title: string, kind: Story['kind'], template?: string): Story {
  const now = new Date().toISOString();
  const base: Story = {
    id: crypto.randomUUID(),
    title,
    kind,
    subtitle: '让故事，在山河之间展开',
    era: kind === 'travel' ? '旅行手记' : '自由探索',
    description: '从一个问题、一处地点，开始你的故事。',
    events: [],
    markers: [],
    routes: [],
    riverChannels: [],
    layers: {
      elevation: true,
      admin: false,
      terrain: false,
      rivers: true,
      lakes: true,
      mountains: true,
      routes: true,
      connections: false,
    },
    view: { center: [112.4, 30.7], zoom: 4.5, pitch: 0 },
    revision: 0,
    createdAt: now,
    updatedAt: now,
  };
  if (template === 'sushi') {
    return {
      ...base,
      kind: 'biography',
      subtitle: '一蓑烟雨任平生',
      era: '北宋 · 1037—1101',
      description: '从眉山出发，越过山川，走过宦海。在地理的经纬中，重读东坡的一生。',
      events: [...structuredClone(suEvents), suDeparture()].sort((a, b) => a.year - b.year),
      routes: [
        {
          id: 'su-route',
          label: '人生节点关系 · 不代表行程',
          coordinates: suEvents.map((e) => e.coordinates),
          color: '#ad795a',
          approximate: true,
        },
        suFirstJourney(),
      ],
    };
  }
  if (template === 'five') {
    const events = [
      event(
        'five-907',
        907,
        '唐亡，后梁建立',
        '汴州',
        [114.307, 34.797],
        '朱温建立后梁，唐朝结束。此后中原王朝频繁更替，南方诸国并立。',
        'turning',
      ),
      event(
        'five-923',
        923,
        '后唐定都洛阳',
        '洛阳',
        [112.454, 34.62],
        '李存勖建立后唐，同年灭后梁，以洛阳为都。',
        'career',
      ),
      event(
        'five-936',
        936,
        '后晋建立',
        '太原',
        [112.549, 37.87],
        '石敬瑭借助契丹力量建立后晋。标记为起兵所在太原。',
        'turning',
      ),
      event(
        'five-937',
        937,
        '南唐兴起',
        '金陵',
        [118.797, 32.061],
        '李昪建立南唐，以金陵为都。江南经济与文化继续发展。',
        'culture',
      ),
      event(
        'five-947',
        947,
        '后汉建立',
        '太原',
        [112.549, 37.87],
        '刘知远在太原称帝，建立后汉，随后进入汴京。',
        'career',
      ),
      event(
        'five-951',
        951,
        '后周建立',
        '汴京',
        [114.307, 34.797],
        '郭威建立后周。后周成为五代中的最后一个中原王朝。',
        'career',
      ),
      event(
        'five-960',
        960,
        '陈桥兵变，宋兴',
        '陈桥',
        [114.46, 35.05],
        '赵匡胤建立宋朝，五代结束。南方诸国及北汉此后陆续纳入宋朝。',
        'turning',
      ),
      event(
        'five-978',
        978,
        '吴越纳土归宋',
        '杭州',
        [120.155, 30.274],
        '钱俶纳土归宋，吴越政权结束。',
        'turning',
      ),
      event(
        'five-979',
        979,
        '北汉灭亡',
        '太原',
        [112.549, 37.87],
        '宋灭北汉，通常以此作为五代十国这一较长时段的终点。',
        'turning',
      ),
    ].map((e) => ({ ...e, source: fiveSource }));
    return {
      ...base,
      kind: 'history',
      subtitle: '山河离合，人间兴替',
      era: '907—979 · 五代十国',
      description:
        '从唐末到宋初，沿着城池与江河，观察王朝更替与地方兴衰。此版本展示事件地点，尚未复原各年历史疆界。',
      events,
      view: { center: [114.3, 33.8], zoom: 4.8, pitch: 0 },
    };
  }
  if (template === 'travel') {
    const events = [
      event(
        'trip-1',
        1,
        '杭州 · 湖山之间',
        '杭州',
        [120.155, 30.274],
        '第一天：从西湖出发，步行苏堤，记录沿途的风景。此路线为行程构想，请自行核对交通与开放时间。',
        'travel',
      ),
      event(
        'trip-2',
        2,
        '湖州 · 水乡慢行',
        '湖州',
        [120.088, 30.894],
        '第二天：沿江南水网向北，留一天给小镇、茶馆和河岸。',
        'travel',
      ),
      event(
        'trip-3',
        3,
        '苏州 · 园林一日',
        '苏州',
        [120.585, 31.299],
        '第三天：在园林与街巷之间散步，为这次江南之旅收尾。',
        'travel',
      ),
    ].map(({ source: _source, ...e }) => ({ ...e, confidence: 'unverified' as const }));
    return {
      ...base,
      kind: 'travel',
      subtitle: '把日子，交给江南',
      era: '3 天 · 江南漫游',
      description: '一条从西湖到园林的旅行灵感路线。',
      events,
      routes: [
        {
          id: 'trip-route',
          label: '江南三日 · 路线构想',
          coordinates: events.map((e) => e.coordinates),
          color: '#507e72',
          approximate: true,
        },
      ],
      view: { center: [120.4, 30.8], zoom: 7, pitch: 0 },
    };
  }
  return base;
}
export const seedStories = () => [
  createStory('苏轼的一生', 'biography', 'sushi'),
  createStory('五代十国', 'history', 'five'),
  createStory('江南三日漫游', 'travel', 'travel'),
];
